"""[ADD] tables with schema

Revision ID: b4078bee4992
Revises: 
Create Date: 2026-06-07 12:44:40.824481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4078bee4992'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('serial', sa.String(length=50), nullable=True),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_devices')),
    sa.UniqueConstraint('serial', name=op.f('uq_devices_serial')),
    schema='gaea'
    )
    op.create_table('plants',
    sa.Column('type', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plants')),
    schema='gaea'
    )
    op.create_table('locations',
    sa.Column('plant_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['plant_id'], ['gaea.plants.id'], name=op.f('fk_locations_plant_id_plants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_locations')),
    schema='gaea'
    )
    op.create_table('measurements',
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['gaea.devices.id'], name=op.f('fk_measurements_device_id_devices')),
    sa.ForeignKeyConstraint(['location_id'], ['gaea.locations.id'], name=op.f('fk_measurements_location_id_locations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_measurements')),
    schema='gaea'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('measurements', schema='gaea')
    op.drop_table('locations', schema='gaea')
    op.drop_table('plants', schema='gaea')
    op.drop_table('devices', schema='gaea')
    # ### end Alembic commands ###
