"""Create tables, schema

Revision ID: de51e04774ac
Revises: 
Create Date: 2026-06-16 21:47:44.037320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de51e04774ac'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices_ref',
    sa.Column('description', sa.String(length=100), nullable=False, comment='Common way to describe this sensor.'),
    sa.Column('communication_type', sa.String(length=10), nullable=False, comment='From list: e.g., serial.'),
    sa.Column('reading_units', sa.String(length=10), nullable=True, comment='From list: e.g., farad, volts, celsius.'),
    sa.Column('reading_min', sa.Float(precision=3), nullable=True, comment='Minimum possible reading value.'),
    sa.Column('reading_max', sa.Float(precision=3), nullable=True, comment='Maximum possible reading value.'),
    sa.Column('reading_precision', sa.Float(precision=3), nullable=True, comment='Possible variance in reading.'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_devices_ref')),
    schema='gaea'
    )
    op.create_table('plants',
    sa.Column('name_common', sa.String(length=20), nullable=True, comment='Common name.'),
    sa.Column('class_common', sa.String(length=10), nullable=True, comment='Common classification like fruit, herb.'),
    sa.Column('name_family', sa.String(length=20), nullable=True, comment='Scientific name of the family.'),
    sa.Column('name_genus', sa.String(length=20), nullable=True, comment='Scientific name of the genus.'),
    sa.Column('name_species', sa.String(length=20), nullable=True, comment='Scientific name of the species.'),
    sa.Column('planting_season', sa.String(length=10), nullable=True, comment='String season, e.g., spring, winter.'),
    sa.Column('soil_quality', sa.Integer(), nullable=True, comment='0-10 where 0 is poor and 10 is fertile.'),
    sa.Column('soil_moisture', sa.Integer(), nullable=True, comment='0-10 where 0 is dry and 10 is wet.'),
    sa.Column('sunlight', sa.Integer(), nullable=True, comment='0-10 where 0 is no direct and 10 is full sun.'),
    sa.Column('wind', sa.Integer(), nullable=True, comment='0-10 where 0 is sheltered  and 10 is open.'),
    sa.Column('pests', sa.String(length=100), nullable=True, comment='Known pests and diseases.'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plants')),
    schema='gaea'
    )
    op.create_table('devices',
    sa.Column('serial', sa.String(length=20), nullable=True, comment='Device Serial Number, unique but not PK.'),
    sa.Column('type', sa.Integer(), nullable=True, comment='FK to reference table with metadata.'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['type'], ['gaea.devices_ref.id'], name=op.f('fk_devices_type_devices_ref'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_devices')),
    sa.UniqueConstraint('serial', name=op.f('uq_devices_serial')),
    schema='gaea'
    )
    op.create_table('locations',
    sa.Column('nickname', sa.String(length=15), nullable=True, comment="Name for the location, e.g. 'Kitchen', 'Garden'."),
    sa.Column('owner', sa.String(length=50), nullable=True, comment="Owner of the location, e.g. 'Me', 'Public'."),
    sa.Column('gps_lat', sa.Float(precision=8), nullable=True, comment='GPS Latitude value'),
    sa.Column('gps_long', sa.Float(precision=8), nullable=True, comment='GPS Latitude value'),
    sa.Column('type', sa.String(length=10), nullable=False, comment='String description of location'),
    sa.Column('plant_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['plant_id'], ['gaea.plants.id'], name=op.f('fk_locations_plant_id_plants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_locations')),
    schema='gaea'
    )
    op.create_table('measurements',
    sa.Column('timestamp', sa.DateTime(), nullable=True, comment='%Y-%m-%d %H:%M:%S. Set by API, not the sensor.'),
    sa.Column('value', sa.Float(precision=5), nullable=True, comment='Sensor raw reading.'),
    sa.Column('device_id', sa.Integer(), nullable=True, comment='FK to the device that made the reading.'),
    sa.Column('location_id', sa.Integer(), nullable=True, comment='FK to where this reading was done.'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['gaea.devices.id'], name=op.f('fk_measurements_device_id_devices')),
    sa.ForeignKeyConstraint(['location_id'], ['gaea.locations.id'], name=op.f('fk_measurements_location_id_locations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_measurements')),
    schema='gaea'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('measurements', schema='gaea')
    op.drop_table('locations', schema='gaea')
    op.drop_table('devices', schema='gaea')
    op.drop_table('plants', schema='gaea')
    op.drop_table('devices_ref', schema='gaea')
    # ### end Alembic commands ###
